Repository theohbrothers/docker-kubectl, pull requests merged in 2023-08, with the labels that each got.

#64 Refactor: Move versions from `VARIANTS.ps1` to `versions.json`
  generate/definitions/VARIANTS.ps1
  generate/definitions/versions.json
Labels: refactor

#65 Feature (ci): Add cron to bump variants
  .github/workflows/cron.yml
  Update-Versions.ps1
  generate/definitions/FILES.ps1
  generate/templates/.github/workflows/cron.yml.ps1
Labels: feature

#66 Enhancement (ci): Add `on: merge_group` for merge queue support
  .github/workflows/ci-master-pr.yml
  generate/templates/.github/workflows/ci-master-pr.yml.ps1
Labels: enhancement

#67 Enhancement (ci): Add `-DryRun` switch to perform dry run
  Update-Versions.ps1
Labels: enhancement

#68 Enhancement (ci): Add args to `Create-PR` function in `Update-Versions.ps1`
  Update-Versions.ps1
Labels: enhancement

#69 Enhancement (ci): Add support for adding new versions in `versions.json` using `Update-Versions.ps1`
  README.md
  Update-Versions.ps1
  generate/templates/README.md.ps1
Labels: enhancement

#70 Enhancement (ci): Add `-PR` switch in `Update-Versions.ps1` to control whether to open PRs for each updated version in `versions.json`
  .github/workflows/cron.yml
  README.md
  Update-Versions.ps1
  generate/templates/.github/workflows/cron.yml.ps1
  generate/templates/README.md.ps1
Labels: enhancement

#71 Enhancement (ci): Force push to branch before creating PR in `Update-Versions.ps1`
  Update-Versions.ps1
Labels: enhancement

#72 Enhancement (ci): Use existing PR if it exists in `Update-Versions.ps1`
  Update-Versions.ps1
Labels: enhancement

#73 Enhancement: Bump base image to `alpine:3.15`
  .github/workflows/ci-master-pr.yml
  README.md
  generate/definitions/VARIANTS.ps1
  variants/v1.14.10-alpine-3.15/Dockerfile
  variants/v1.14.10-alpine-3.15/docker-entrypoint.sh
  variants/v1.14.10-envsubst-git-jq-kustomize-sops-ssh-alpine-3.15/Dockerfile
  variants/v1.14.10-envsubst-git-jq-kustomize-sops-ssh-alpine-3.15/docker-entrypoint.sh
  variants/v1.15.12-alpine-3.15/Dockerfile
  variants/v1.15.12-alpine-3.15/docker-entrypoint.sh
  variants/v1.15.12-envsubst-git-jq-kustomize-sops-ssh-alpine-3.15/Dockerfile
  variants/v1.15.12-envsubst-git-jq-kustomize-sops-ssh-alpine-3.15/docker-entrypoint.sh
  variants/v1.16.15-alpine-3.15/Dockerfile
  variants/v1.16.15-alpine-3.15/docker-entrypoint.sh
  variants/v1.16.15-envsubst-git-jq-kustomize-sops-ssh-alpine-3.15/Dockerfile
  variants/v1.16.15-envsubst-git-jq-kustomize-sops-ssh-alpine-3.15/docker-entrypoint.sh
  variants/v1.17.17-alpine-3.15/Dockerfile
  variants/v1.17.17-alpine-3.15/docker-entrypoint.sh
  variants/v1.17.17-envsubst-git-jq-kustomize-sops-ssh-alpine-3.15/Dockerfile
  variants/v1.17.17-envsubst-git-jq-kustomize-sops-ssh-alpine-3.15/docker-entrypoint.sh
  variants/v1.18.20-alpine-3.15/Dockerfile
  variants/v1.18.20-alpine-3.15/docker-entrypoint.sh
  variants/v1.18.20-envsubst-git-jq-kustomize-sops-ssh-alpine-3.15/Dockerfile
  variants/v1.18.20-envsubst-git-jq-kustomize-sops-ssh-alpine-3.15/docker-entrypoint.sh
  variants/v1.19.16-alpine-3.15/Dockerfile
  variants/v1.19.16-alpine-3.15/docker-entrypoint.sh
  variants/v1.19.16-envsubst-git-jq-kustomize-sops-ssh-alpine-3.15/Dockerfile
  variants/v1.19.16-envsubst-git-jq-kustomize-sops-ssh-alpine-3.15/docker-entrypoint.sh
  variants/v1.20.15-alpine-3.15/Dockerfile
  variants/v1.20.15-alpine-3.15/docker-entrypoint.sh
  variants/v1.20.15-envsubst-git-jq-kustomize-sops-ssh-alpine-3.15/Dockerfile
  variants/v1.20.15-envsubst-git-jq-kustomize-sops-ssh-alpine-3.15/docker-entrypoint.sh
  variants/v1.21.14-alpine-3.15/Dockerfile
  variants/v1.21.14-alpine-3.15/docker-entrypoint.sh
  variants/v1.21.14-envsubst-git-jq-kustomize-sops-ssh-alpine-3.15/Dockerfile
  variants/v1.21.14-envsubst-git-jq-kustomize-sops-ssh-alpine-3.15/docker-entrypoint.sh
  variants/v1.22.17-alpine-3.15/Dockerfile
  variants/v1.22.17-alpine-3.15/docker-entrypoint.sh
  variants/v1.22.17-envsubst-git-jq-kustomize-sops-ssh-alpine-3.15/Dockerfile
  variants/v1.22.17-envsubst-git-jq-kustomize-sops-ssh-alpine-3.15/docker-entrypoint.sh
  variants/v1.23.17-alpine-3.15/Dockerfile
  variants/v1.23.17-alpine-3.15/docker-entrypoint.sh
  variants/v1.23.17-envsubst-git-jq-kustomize-sops-ssh-alpine-3.15/Dockerfile
  variants/v1.23.17-envsubst-git-jq-kustomize-sops-ssh-alpine-3.15/docker-entrypoint.sh
  variants/v1.24.15-alpine-3.15/Dockerfile
  variants/v1.24.15-alpine-3.15/docker-entrypoint.sh
  variants/v1.24.15-envsubst-git-jq-kustomize-sops-ssh-alpine-3.15/Dockerfile
  variants/v1.24.15-envsubst-git-jq-kustomize-sops-ssh-alpine-3.15/docker-entrypoint.sh
  variants/v1.25.11-alpine-3.15/Dockerfile
  variants/v1.25.11-alpine-3.15/docker-entrypoint.sh
  variants/v1.25.11-envsubst-git-jq-kustomize-sops-ssh-alpine-3.15/Dockerfile
  variants/v1.25.11-envsubst-git-jq-kustomize-sops-ssh-alpine-3.15/docker-entrypoint.sh
  variants/v1.26.6-alpine-3.15/Dockerfile
  variants/v1.26.6-alpine-3.15/docker-entrypoint.sh
  variants/v1.26.6-envsubst-git-jq-kustomize-sops-ssh-alpine-3.15/Dockerfile
  variants/v1.26.6-envsubst-git-jq-kustomize-sops-ssh-alpine-3.15/docker-entrypoint.sh
  variants/v1.27.3-alpine-3.15/Dockerfile
  variants/v1.27.3-alpine-3.15/docker-entrypoint.sh
  variants/v1.27.3-envsubst-git-jq-kustomize-sops-ssh-alpine-3.15/Dockerfile
  variants/v1.27.3-envsubst-git-jq-kustomize-sops-ssh-alpine-3.15/docker-entrypoint.sh
Labels: enhancement

#74 Fix (ci): Fix syntax error in `Update-Versions.ps1`
  Update-Versions.ps1
Labels: fix

#75 Fix (ci): Fix PR title and body in `Update-Versions.ps1`
  Update-Versions.ps1
Labels: fix

#76 Enhancement: Add v1.28.1 variants
  .github/workflows/ci-master-pr.yml
  README.md
  generate/definitions/versions.json
  variants/v1.28.1-alpine-3.15/Dockerfile
  variants/v1.28.1-alpine-3.15/docker-entrypoint.sh
  variants/v1.28.1-envsubst-git-jq-kustomize-sops-ssh-alpine-3.15/Dockerfile
  variants/v1.28.1-envsubst-git-jq-kustomize-sops-ssh-alpine-3.15/docker-entrypoint.sh
Labels: enhancement

#81 Enhancement (ci): Add support for assigning milestone to PRs in `Update-Versions.ps1`
  Update-Versions.ps1
Labels: enhancement

#82 Fix (ci): Checkout to `master` after opening each PR `Update-Versions.ps1`
  Update-Versions.ps1
Labels: fix

#83 Enhancement (ci): Add `Execute-Command` function that terminates on non-zero exit code in `Update-Versions.ps1`
  Update-Versions.ps1
Labels: enhancement

#84 Fix (ci): Get existing milestone in `Update-Versions.ps1`
  Update-Versions.ps1
Labels: fix
