Repository theohbrothers/docker-kubectl, pull requests merged in 2023-09, with the labels that each got.

#86 Fix (ci): Honor `-ErrorAction` in `Execute-Command` in `Update-Versions.ps1`
  Update-Versions.ps1
Labels: fix

#87 Hotfix (ci): Change `cron` to run every hour
  .github/workflows/cron.yml
  generate/templates/.github/workflows/cron.yml.ps1
Labels: hotfix

#77 Enhancement: Bump v1.27 variants to 1.27.5
  .github/workflows/ci-master-pr.yml
  README.md
  generate/definitions/versions.json
  variants/v1.27.5-alpine-3.15/Dockerfile
  variants/v1.27.5-alpine-3.15/docker-entrypoint.sh
  variants/v1.27.5-envsubst-git-jq-kustomize-sops-ssh-alpine-3.15/Dockerfile
  variants/v1.27.5-envsubst-git-jq-kustomize-sops-ssh-alpine-3.15/docker-entrypoint.sh
Labels: enhancement

#88 Refactor (ci): Use separate lines for `needs` key values to prevent merge conflicts
  .github/workflows/ci-master-pr.yml
  generate/templates/.github/workflows/ci-master-pr.yml.ps1
Labels: refactor

#78 Enhancement: Bump v1.26 variants to 1.26.8
  .github/workflows/ci-master-pr.yml
  README.md
  generate/definitions/versions.json
  variants/v1.26.8-alpine-3.15/Dockerfile
  variants/v1.26.8-alpine-3.15/docker-entrypoint.sh
  variants/v1.26.8-envsubst-git-jq-kustomize-sops-ssh-alpine-3.15/Dockerfile
  variants/v1.26.8-envsubst-git-jq-kustomize-sops-ssh-alpine-3.15/docker-entrypoint.sh
Labels: enhancement

#79 Enhancement: Bump v1.25 variants to 1.25.13
  .github/workflows/ci-master-pr.yml
  README.md
  generate/definitions/versions.json
  variants/v1.25.13-alpine-3.15/Dockerfile
  variants/v1.25.13-alpine-3.15/docker-entrypoint.sh
  variants/v1.25.13-envsubst-git-jq-kustomize-sops-ssh-alpine-3.15/Dockerfile
  variants/v1.25.13-envsubst-git-jq-kustomize-sops-ssh-alpine-3.15/docker-entrypoint.sh
Labels: enhancement

#80 Enhancement: Bump v1.24 variants to 1.24.17
  .github/workflows/ci-master-pr.yml
  README.md
  generate/definitions/versions.json
  variants/v1.24.17-alpine-3.15/Dockerfile
  variants/v1.24.17-alpine-3.15/docker-entrypoint.sh
  variants/v1.24.17-envsubst-git-jq-kustomize-sops-ssh-alpine-3.15/Dockerfile
  variants/v1.24.17-envsubst-git-jq-kustomize-sops-ssh-alpine-3.15/docker-entrypoint.sh
Labels: enhancement

#90 Enhancement (ci): Simplify `Update-Versions.ps1` to use `Generate-DockerImageVariantsHelpers`
  Update-Versions.ps1
Labels: enhancement

#91 Enhancement (ci): Update `cron` to run daily with automerge and autorelease
  .github/workflows/cron.yml
  generate/templates/.github/workflows/cron.yml.ps1
Labels: enhancement

#93 Refactor: Do not specify `ConvertFrom-Json -Depth` in `VARIANTS.ps1`
  generate/definitions/VARIANTS.ps1
Labels: refactor

#96 Docs (readme): Update comments in Variant versions section
  README.md
  generate/templates/README.md.ps1
Labels: docs

#97 Fix: Remove need for `ConvertFrom-Json -Depth` in `Update-Versions.ps1`
  Update-Versions.ps1
Labels: fix

#98 Fix: Preserve array when using `ConvertFrom-Json` in `VARIANTS.ps1`
  generate/definitions/VARIANTS.ps1
Labels: fix

#99 Refactor: Pipe to `ConvertFrom-Json` in `VARIANTS.ps1`
  generate/definitions/VARIANTS.ps1
Labels: refactor

#100 Fix: Fix `Update-Versions.ps1` to detect versions correctly
  Update-Versions.ps1
Labels: fix

#101 Enhancement: Bump v1.28 variants to v1.28.2
  .github/workflows/ci-master-pr.yml
  README.md
  generate/definitions/versions.json
  variants/v1.28.2-alpine-3.15/Dockerfile
  variants/v1.28.2-alpine-3.15/docker-entrypoint.sh
  variants/v1.28.2-envsubst-git-jq-kustomize-sops-ssh-alpine-3.15/Dockerfile
  variants/v1.28.2-envsubst-git-jq-kustomize-sops-ssh-alpine-3.15/docker-entrypoint.sh
Labels: enhancement

#102 Enhancement: Bump v1.27 variants to v1.27.6
  .github/workflows/ci-master-pr.yml
  README.md
  generate/definitions/versions.json
  variants/v1.27.6-alpine-3.15/Dockerfile
  variants/v1.27.6-alpine-3.15/docker-entrypoint.sh
  variants/v1.27.6-envsubst-git-jq-kustomize-sops-ssh-alpine-3.15/Dockerfile
  variants/v1.27.6-envsubst-git-jq-kustomize-sops-ssh-alpine-3.15/docker-entrypoint.sh
Labels: enhancement

#104 Enhancement: Bump v1.25 variants to v1.25.14
  .github/workflows/ci-master-pr.yml
  README.md
  generate/definitions/versions.json
  variants/v1.25.14-alpine-3.15/Dockerfile
  variants/v1.25.14-alpine-3.15/docker-entrypoint.sh
  variants/v1.25.14-envsubst-git-jq-kustomize-sops-ssh-alpine-3.15/Dockerfile
  variants/v1.25.14-envsubst-git-jq-kustomize-sops-ssh-alpine-3.15/docker-entrypoint.sh
Labels: enhancement

#103 Enhancement: Bump v1.26 variants to v1.26.9
  .github/workflows/ci-master-pr.yml
  README.md
  generate/definitions/versions.json
  variants/v1.26.9-alpine-3.15/Dockerfile
  variants/v1.26.9-alpine-3.15/docker-entrypoint.sh
  variants/v1.26.9-envsubst-git-jq-kustomize-sops-ssh-alpine-3.15/Dockerfile
  variants/v1.26.9-envsubst-git-jq-kustomize-sops-ssh-alpine-3.15/docker-entrypoint.sh
Labels: enhancement

#106 Enhancement (ci): Remove ` $env:GITHUB_TOKEN` in `Update-Versions.ps1`
  Update-Versions.ps1
Labels: enhancement

#107 Refactor (ci): Use new `versions.json` config
  Update-Versions.ps1
  generate/definitions/VARIANTS.ps1
  generate/definitions/versions.json
Labels: refactor

#108 Fix: Remove invalid param in `Update-Versions.ps1
  Update-Versions.ps1
Labels: fix

#109 Enhancement (ci): Add `workflow_dispatch` to `cron` job
  .github/workflows/cron.yml
  generate/templates/.github/workflows/cron.yml.ps1
Labels: enhancement

#110 Enhancement (ci): Add support for incremental variants
  .github/workflows/ci-master-pr.yml
  generate/definitions/VARIANTS.ps1
  generate/templates/.github/workflows/ci-master-pr.yml.ps1
  generate/templates/Dockerfile.ps1
Labels: enhancement
